import type { Metadata } from "next";
import Header from "../component/layout/Header";
import Footer from "../component/layout/Footer";
import { GlobalProvider } from "./GlobalProvider";
import Script from "next/script";
import "../styles/globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;
import "aos/dist/aos.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
      </head>
      <body>
      <GlobalProvider>
          <Header />
          {children}
          <Footer />
        </GlobalProvider>
        <Script src="/js/jquery-3.6.4.min.js" strategy="beforeInteractive" />
        <Script src="/js/bootstrap.bundle.min.js" strategy="afterInteractive" />
        <Script src="/js/slick.js" strategy="afterInteractive" />
        <Script src="/js/backToTop.js" strategy="afterInteractive" />
        <Script src="/js/aos.js" strategy="afterInteractive" />
        <Script src="/js/moment.min.js" strategy="afterInteractive" />
        <Script src="/js/bootstrap-datetimepicker.min.js" strategy="afterInteractive" />
        <Script src="/js/circle-progress.min.js" strategy="afterInteractive" />
        <Script src="/js/counter.js" strategy="afterInteractive" />
        <Script src="/js/email-decode.min.js" strategy="afterInteractive" />
        <Script src="/js/feather.min.js" strategy="afterInteractive" />
        <Script src="/js/owl.carousel.min.js" strategy="afterInteractive" />
        <Script src="/js/profile-settings.js" strategy="afterInteractive" />
        <Script src="/plugins/intltelinput/js/intlTelInput.js" strategy="afterInteractive"/>
        <Script src="/plugins/intltelinput/js/utils.js" strategy="afterInteractive"/>
        <Script src="/js/script.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}
